# Generated by Django 4.0.5 on 2022-06-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Informacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('altura', models.FloatField(choices=[(1, '<1.60'), (2, '1.60 - 1.65'), (3, '1.65 - 1.70'), (4, '1.70 - 1.75'), (5, '1.75 - 1.80'), (6, '1.80 - 1.85'), (7, '> 1.85')], verbose_name='Altura')),
                ('nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
            ],
        ),
    ]
